export const actions = {
    GET_INBOX_MESSAGES: "GET_INBOX_MESSAGES",
    CREATE_INBOX_MESSAGE: "CREATE_INBOX_MESSAGE",
    CREATE_DRAFT_MESSAGE: "CREATE_DRAFT_MESSAGE", 
    DELETE_DRAFT_MESSAGE: "DELETE_DRAFT_MESSAGE", 
}

export const GET = "GET"
export const POST = "POST"
export const DELETE = "DELETE"